### PR TITLE
Supporting multiple outputs

### PR DESCRIPTION
**Pull request by mbutan**
**Goal**
Allows to launch gst_ichabod with more than one broadcast url or output path. It doesn't change public interface.

**Implementation**
Tiny change in ichabod_sink interface which replaces single variable input by singled list structure.
Also unified the code which attaches mux/sink to bin.

### CODE REVIEW

**Comment by wobbals** [comment]
How unexpected, thank you @mbutan! This doesn't get us any closer to being able to add/remove output sinks dynamically -- is that something that you still are interested in? I've begun to refactor the controller in order to open up a signaling path for changes to the pipeline while it's already in playing state. Let me know if you want me to keep you in the loop about it.

**Comment by mbutan** [comment]
Plan was just to add an option for more than one output sinks the same type, like broadcasting to youtube/twitch at the same time, and set it up just before playing state.
Public interface is still the same:
> -b rtmp:1..
> -b rtmp:2..

**Comment by wobbals** [comment]
Great, thanks. If this works as expected, it's a good start. The webservice won't be able to forward along multiple URLs to the task worker; do you want to expose that at the same time as we merge this PR, or should we just wait for the refactor for dynamic output sinks?

**Comment by mbutan** [comment]
Honestly, I haven't dived into the task worker yet. I'm using locally these changes for own headless implementation.

**Pull request closed without merging**
